### ISSUE TITLE
incorrect ports number in documentation

### ISSUE THREAD

**Issue by aayushus** [pg07codes/fokus#10]
The documentation advises to map ports 5000 to 5000 but looks like the internal port is 3000. It should be - 

docker run -d --name fokus -p 5000:3000 fokus

or 

docker run -d --name fokus -p 3000:3000 fokus

**Comment by pg07codes** [comment]
@mercplus thanks for reporting. @Starttoaster can you confirm this please?

**Comment by Samvid95** [comment]
Yup @mercplus is correct. The internal port is 3000.

**Comment by pg07codes** [comment]
thanks for reporting. can @mercplus or @Samvid95 raise a PR for the bug fix ?

**Comment by Samvid95** [comment]
Sure I opened a PR for the bug fix.

**Comment by pg07codes** [comment]
resolved
