### ISSUE TITLE
Arrows

### ISSUE THREAD

**Issue by AuthorShin** [pg07codes/fokus#14]
these two arrow cover the numbers and field.
(FireFox 96)
<img src="https://i.ibb.co/99L7YK3/Screenshot-2022-05-03-215939.png" alt="Screenshot-2022-05-03-215939" border="0">

**Comment by min0k** [comment]
Hey @pg07codes, I have the fix ready for this issue. Can I get permission to push a PR?

**Comment by min0k** [comment]
@pg07codes Created a [PR](https://github.com/pg07codes/fokus/pull/17) for this issue.

**Comment by pg07codes** [comment]
fixed in #17

**Comment by AuthorShin** [comment]
Still not fixed on https://fokusapp.netlify.app/
