### ISSUE TITLE
404 error when not navigating from UI

### ISSUE THREAD

**Issue by khaki32** [pg07codes/fokus#16]
If you go to a page from an external link, so not from the interface, you get a 404 error. [Example Link](https://fokusapp.netlify.app/notes).

**Comment by khaki32** [comment]
This seems to be an error in the Netfliy configuration. You'll probably want to do something along the lines of redirecting every path to the root path "/", so that React Router can do it's job.

**Comment by pg07codes** [comment]
thanks for reporting @khaki32 . it should be fixed now
